Traceback (most recent call last):
  File "test_m.py", line 334, in <module>
    while MazeGame(Maze.generate(width, height)).play(): pass
  File "test_m.py", line 295, in play
    console.display(str(self.maze))
  File "/Users/singhyogendra/randomgen/AllInOne-Generator/console.py", line 65, in display
    return _display(text)
  File "/Users/singhyogendra/randomgen/AllInOne-Generator/console.py", line 49, in _display
    window.addstr(0, 0, text)
_curses.error: addwstr() returned ERR
Traceback (most recent call last):
  File "test_m.py", line 334, in <module>
    while MazeGame(Maze.generate(width, height)).play(): pass
  File "test_m.py", line 295, in play
    console.display(str(self.maze))
  File "/Users/singhyogendra/randomgen/AllInOne-Generator/console.py", line 65, in display
    return _display(text)
  File "/Users/singhyogendra/randomgen/AllInOne-Generator/console.py", line 49, in _display
    window.addstr(0, 0, text)
_curses.error: addwstr() returned ERR
Traceback (most recent call last):
  File "test_m.py", line 334, in <module>
    while MazeGame(Maze.generate(width, height)).play(): pass
  File "test_m.py", line 295, in play
    console.display(str(self.maze))
  File "/Users/singhyogendra/randomgen/AllInOne-Generator/console.py", line 65, in display
    return _display(text)
  File "/Users/singhyogendra/randomgen/AllInOne-Generator/console.py", line 49, in _display
    window.addstr(0, 0, text)
_curses.error: addwstr() returned ERR
Traceback (most recent call last):
  File "test_m.py", line 334, in <module>
    while MazeGame(Maze.generate(width, height)).play(): pass
  File "test_m.py", line 295, in play
    console.display(str(self.maze))
  File "/Users/singhyogendra/randomgen/AllInOne-Generator/console.py", line 65, in display
    return _display(text)
  File "/Users/singhyogendra/randomgen/AllInOne-Generator/console.py", line 49, in _display
    window.addstr(0, 0, text)
_curses.error: addwstr() returned ERR
Traceback (most recent call last):
  File "test_m.py", line 334, in <module>
    while MazeGame(Maze.generate(width, height)).play(): pass
  File "test_m.py", line 295, in play
    console.display(str(self.maze))
  File "/Users/singhyogendra/randomgen/AllInOne-Generator/console.py", line 65, in display
    return _display(text)
  File "/Users/singhyogendra/randomgen/AllInOne-Generator/console.py", line 49, in _display
    window.addstr(0, 0, text)
_curses.error: addwstr() returned ERR
